
/* File generated by gen_cfile.py. Should not be modified. */

#include "masterdic.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER16 position_1 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
INTEGER16 position_2 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
INTEGER16 position_3 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS32 counter_1 = 0x0;		/* Mapped at index 0x3000, subindex 0x00 */
UNS32 counter_2 = 0x0;		/* Mapped at index 0x3001, subindex 0x00 */
UNS32 counter_3 = 0x0;		/* Mapped at index 0x3003, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 masterdic_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 masterdic_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 masterdic_iam_a_slave = 0;

TIMER_HANDLE masterdic_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   b'Device Type'. */
                    UNS32 masterdic_obj1000 = 0x0;	/* 0 */
                    const CONSTSTORE subindex masterdic_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), .pObject=&masterdic_obj1000 }
                     };

/* index 0x1001 :   b'Error Register'. */
                    UNS8 masterdic_obj1001 = 0x0;	/* 0 */
                    const CONSTSTORE subindex masterdic_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 masterdic_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 masterdic_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t masterdic_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), .pObject=(void*)&masterdic_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), .pObject=(void*)&masterdic_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 masterdic_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 masterdic_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 masterdic_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 masterdic_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 masterdic_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   b'Consumer Heartbeat Time'. */
                    UNS8 masterdic_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex masterdic_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1016[0] }
                     };

/* index 0x1017 :   b'Producer Heartbeat Time'. */
                    UNS16 masterdic_obj1017 = 0x0;	/* 0 */
                    ODCallback_t masterdic_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1017 }
                     };

/* index 0x1018 :   b'Identity'. */
                    UNS8 masterdic_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 masterdic_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 masterdic_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 masterdic_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 masterdic_obj1018_Serial_Number = 0x0;	/* 0 */
                    const CONSTSTORE subindex masterdic_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), .pObject=&masterdic_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), .pObject=&masterdic_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), .pObject=&masterdic_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), .pObject=&masterdic_obj1018_Serial_Number }
                     };

/* index 0x1280 :   b'Client SDO 1 Parameter'. */
                    UNS8 masterdic_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 masterdic_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 masterdic_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 masterdic_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    const CONSTSTORE subindex masterdic_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   b'Receive PDO 1 Parameter'. */
                    UNS8 masterdic_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 masterdic_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 masterdic_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 masterdic_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterdic_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterdic_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterdic_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    const CONSTSTORE subindex masterdic_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   b'Receive PDO 2 Parameter'. */
                    UNS8 masterdic_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 masterdic_obj1401_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 masterdic_obj1401_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 masterdic_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterdic_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterdic_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterdic_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    const CONSTSTORE subindex masterdic_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   b'Receive PDO 3 Parameter'. */
                    UNS8 masterdic_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 masterdic_obj1402_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 masterdic_obj1402_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 masterdic_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterdic_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterdic_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterdic_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    const CONSTSTORE subindex masterdic_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1402_SYNC_start_value }
                     };

/* index 0x1600 :   b'Receive PDO 1 Mapping'. */
                    UNS8 masterdic_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1600[] = 
                    {
                      0x30000020	/* 805306400 */
                    };
                    const CONSTSTORE subindex masterdic_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1600[0] }
                     };

/* index 0x1601 :   b'Receive PDO 2 Mapping'. */
                    UNS8 masterdic_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1601[] = 
                    {
                      0x30010020	/* 805371936 */
                    };
                    const CONSTSTORE subindex masterdic_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1601[0] }
                     };

/* index 0x1602 :   b'Receive PDO 3 Mapping'. */
                    UNS8 masterdic_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1602[] = 
                    {
                      0x30030020	/* 805503008 */
                    };
                    const CONSTSTORE subindex masterdic_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1602[0] }
                     };

/* index 0x1800 :   b'Transmit PDO 1 Parameter'. */
                    UNS8 masterdic_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 masterdic_obj1800_COB_ID_used_by_PDO = 0x201;	/* 513 */
                    UNS8 masterdic_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 masterdic_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterdic_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterdic_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterdic_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t masterdic_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   b'Transmit PDO 2 Parameter'. */
                    UNS8 masterdic_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 masterdic_obj1801_COB_ID_used_by_PDO = 0x202;	/* 514 */
                    UNS8 masterdic_obj1801_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 masterdic_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterdic_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterdic_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterdic_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t masterdic_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   b'Transmit PDO 3 Parameter'. */
                    UNS8 masterdic_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 masterdic_obj1802_COB_ID_used_by_PDO = 0x203;	/* 515 */
                    UNS8 masterdic_obj1802_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 masterdic_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterdic_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterdic_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterdic_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t masterdic_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), .pObject=&masterdic_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1802_SYNC_start_value }
                     };

/* index 0x1A00 :   b'Transmit PDO 1 Mapping'. */
                    UNS8 masterdic_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1A00[] = 
                    {
                      0x20000010	/* 536870928 */
                    };
                    const CONSTSTORE subindex masterdic_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1A00[0] }
                     };

/* index 0x1A01 :   b'Transmit PDO 2 Mapping'. */
                    UNS8 masterdic_highestSubIndex_obj1A01 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1A01[] = 
                    {
                      0x20010010	/* 536936464 */
                    };
                    const CONSTSTORE subindex masterdic_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1A01[0] }
                     };

/* index 0x1A02 :   b'Transmit PDO 3 Mapping'. */
                    UNS8 masterdic_highestSubIndex_obj1A02 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1A02[] = 
                    {
                      0x20020010	/* 537002000 */
                    };
                    const CONSTSTORE subindex masterdic_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1A02[0] }
                     };

/* index 0x1F20 :   b'Store DCF'. */
                    UNS8 masterdic_highestSubIndex_obj1F20 = 1; /* number of subindex - 1*/
                    UNS8* masterdic_obj1F20[] = 
                    {
                      ""
                    };
                    const CONSTSTORE subindex masterdic_Index1F20[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1F20 },
                       { RW, domain, 0, .pObject=&masterdic_obj1F20[0] }
                     };

/* index 0x1F21 :   b'Storage Format'. */
                    UNS8 masterdic_highestSubIndex_obj1F21 = 1; /* number of subindex - 1*/
                    INTEGER8 masterdic_obj1F21[] = 
                    {
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex masterdic_Index1F21[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1F21 },
                       { RW, int8, sizeof (INTEGER8), .pObject=&masterdic_obj1F21[0] }
                     };

/* index 0x1F22 :   b'Concise DCF'. */
                    UNS8 masterdic_highestSubIndex_obj1F22 = 3; /* number of subindex - 1*/
                    UNS8* masterdic_obj1F22[] = 
                    {
                      "",
                      "",
                      ""
                    };
                    const CONSTSTORE subindex masterdic_Index1F22[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1F22 },
                       { RW, domain, 0, .pObject=&masterdic_obj1F22[0] },
                       { RW, domain, 0, .pObject=&masterdic_obj1F22[1] },
                       { RW, domain, 0, .pObject=&masterdic_obj1F22[2] }
                     };

/* index 0x1F50 :   b'Download Program Data'. */
                    UNS8 masterdic_highestSubIndex_obj1F50 = 1; /* number of subindex - 1*/
                    UNS8* masterdic_obj1F50[] = 
                    {
                      ""
                    };
                    const CONSTSTORE subindex masterdic_Index1F50[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1F50 },
                       { RW, domain, 0, .pObject=&masterdic_obj1F50[0] }
                     };

/* index 0x1F51 :   b'Program Control'. */
                    UNS8 masterdic_highestSubIndex_obj1F51 = 1; /* number of subindex - 1*/
                    UNS8 masterdic_obj1F51[] = 
                    {
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex masterdic_Index1F51[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1F51 },
                       { RW, uint8, sizeof (UNS8), .pObject=&masterdic_obj1F51[0] }
                     };

/* index 0x1F52 :   b'Verify Application Software'. */
                    UNS8 masterdic_highestSubIndex_obj1F52 = 2; /* number of subindex - 1*/
                    UNS32 masterdic_obj1F52_Application_software_date = 0x0;	/* 0 */
                    UNS32 masterdic_obj1F52_Application_sofware_time = 0x0;	/* 0 */
                    const CONSTSTORE subindex masterdic_Index1F52[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1F52 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1F52_Application_software_date },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1F52_Application_sofware_time }
                     };

/* index 0x1F53 :   b'Expected Application SW Date'. */
                    UNS8 masterdic_highestSubIndex_obj1F53 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1F53[] = 
                    {
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex masterdic_Index1F53[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1F53 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1F53[0] }
                     };

/* index 0x1F55 :   b'Expected Application SW Time'. */
                    UNS8 masterdic_highestSubIndex_obj1F55 = 1; /* number of subindex - 1*/
                    UNS32 masterdic_obj1F55[] = 
                    {
                      0x0	/* 0 */
                    };
                    const CONSTSTORE subindex masterdic_Index1F55[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&masterdic_highestSubIndex_obj1F55 },
                       { RW, uint32, sizeof (UNS32), .pObject=&masterdic_obj1F55[0] }
                     };

/* index 0x2000 :   Mapped variable b'position_1' */
                    ODCallback_t position_1_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index2000[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), .pObject=&position_1 }
                     };

/* index 0x2001 :   Mapped variable b'position_2' */
                    ODCallback_t position_2_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index2001[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), .pObject=&position_2 }
                     };

/* index 0x2002 :   Mapped variable b'position_3' */
                    ODCallback_t position_3_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index2002[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), .pObject=&position_3 }
                     };

/* index 0x3000 :   Mapped variable b'counter_1' */
                    ODCallback_t counter_1_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index3000[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&counter_1 }
                     };

/* index 0x3001 :   Mapped variable b'counter_2' */
                    ODCallback_t counter_2_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index3001[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&counter_2 }
                     };

/* index 0x3003 :   Mapped variable b'counter_3' */
                    ODCallback_t counter_3_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex masterdic_Index3003[] = 
                     {
                       { RW, uint32, sizeof (UNS32), .pObject=&counter_3 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const CONSTSTORE indextable masterdic_objdict[] = 
{
  { (const CONSTSTORE subindex* const)masterdic_Index1000,sizeof(masterdic_Index1000)/sizeof(masterdic_Index1000[0]), 0x1000},
  { (const CONSTSTORE subindex* const)masterdic_Index1001,sizeof(masterdic_Index1001)/sizeof(masterdic_Index1001[0]), 0x1001},
  { (const CONSTSTORE subindex* const)masterdic_Index1016,sizeof(masterdic_Index1016)/sizeof(masterdic_Index1016[0]), 0x1016},
  { (const CONSTSTORE subindex* const)masterdic_Index1017,sizeof(masterdic_Index1017)/sizeof(masterdic_Index1017[0]), 0x1017},
  { (const CONSTSTORE subindex* const)masterdic_Index1018,sizeof(masterdic_Index1018)/sizeof(masterdic_Index1018[0]), 0x1018},
  { (const CONSTSTORE subindex* const)masterdic_Index1280,sizeof(masterdic_Index1280)/sizeof(masterdic_Index1280[0]), 0x1280},
  { (const CONSTSTORE subindex* const)masterdic_Index1400,sizeof(masterdic_Index1400)/sizeof(masterdic_Index1400[0]), 0x1400},
  { (const CONSTSTORE subindex* const)masterdic_Index1401,sizeof(masterdic_Index1401)/sizeof(masterdic_Index1401[0]), 0x1401},
  { (const CONSTSTORE subindex* const)masterdic_Index1402,sizeof(masterdic_Index1402)/sizeof(masterdic_Index1402[0]), 0x1402},
  { (const CONSTSTORE subindex* const)masterdic_Index1600,sizeof(masterdic_Index1600)/sizeof(masterdic_Index1600[0]), 0x1600},
  { (const CONSTSTORE subindex* const)masterdic_Index1601,sizeof(masterdic_Index1601)/sizeof(masterdic_Index1601[0]), 0x1601},
  { (const CONSTSTORE subindex* const)masterdic_Index1602,sizeof(masterdic_Index1602)/sizeof(masterdic_Index1602[0]), 0x1602},
  { (const CONSTSTORE subindex* const)masterdic_Index1800,sizeof(masterdic_Index1800)/sizeof(masterdic_Index1800[0]), 0x1800},
  { (const CONSTSTORE subindex* const)masterdic_Index1801,sizeof(masterdic_Index1801)/sizeof(masterdic_Index1801[0]), 0x1801},
  { (const CONSTSTORE subindex* const)masterdic_Index1802,sizeof(masterdic_Index1802)/sizeof(masterdic_Index1802[0]), 0x1802},
  { (const CONSTSTORE subindex* const)masterdic_Index1A00,sizeof(masterdic_Index1A00)/sizeof(masterdic_Index1A00[0]), 0x1A00},
  { (const CONSTSTORE subindex* const)masterdic_Index1A01,sizeof(masterdic_Index1A01)/sizeof(masterdic_Index1A01[0]), 0x1A01},
  { (const CONSTSTORE subindex* const)masterdic_Index1A02,sizeof(masterdic_Index1A02)/sizeof(masterdic_Index1A02[0]), 0x1A02},
  { (const CONSTSTORE subindex* const)masterdic_Index1F20,sizeof(masterdic_Index1F20)/sizeof(masterdic_Index1F20[0]), 0x1F20},
  { (const CONSTSTORE subindex* const)masterdic_Index1F21,sizeof(masterdic_Index1F21)/sizeof(masterdic_Index1F21[0]), 0x1F21},
  { (const CONSTSTORE subindex* const)masterdic_Index1F22,sizeof(masterdic_Index1F22)/sizeof(masterdic_Index1F22[0]), 0x1F22},
  { (const CONSTSTORE subindex* const)masterdic_Index1F50,sizeof(masterdic_Index1F50)/sizeof(masterdic_Index1F50[0]), 0x1F50},
  { (const CONSTSTORE subindex* const)masterdic_Index1F51,sizeof(masterdic_Index1F51)/sizeof(masterdic_Index1F51[0]), 0x1F51},
  { (const CONSTSTORE subindex* const)masterdic_Index1F52,sizeof(masterdic_Index1F52)/sizeof(masterdic_Index1F52[0]), 0x1F52},
  { (const CONSTSTORE subindex* const)masterdic_Index1F53,sizeof(masterdic_Index1F53)/sizeof(masterdic_Index1F53[0]), 0x1F53},
  { (const CONSTSTORE subindex* const)masterdic_Index1F55,sizeof(masterdic_Index1F55)/sizeof(masterdic_Index1F55[0]), 0x1F55},
  { (const CONSTSTORE subindex* const)masterdic_Index2000,sizeof(masterdic_Index2000)/sizeof(masterdic_Index2000[0]), 0x2000},
  { (const CONSTSTORE subindex* const)masterdic_Index2001,sizeof(masterdic_Index2001)/sizeof(masterdic_Index2001[0]), 0x2001},
  { (const CONSTSTORE subindex* const)masterdic_Index2002,sizeof(masterdic_Index2002)/sizeof(masterdic_Index2002[0]), 0x2002},
  { (const CONSTSTORE subindex* const)masterdic_Index3000,sizeof(masterdic_Index3000)/sizeof(masterdic_Index3000[0]), 0x3000},
  { (const CONSTSTORE subindex* const)masterdic_Index3001,sizeof(masterdic_Index3001)/sizeof(masterdic_Index3001[0]), 0x3001},
  { (const CONSTSTORE subindex* const)masterdic_Index3003,sizeof(masterdic_Index3003)/sizeof(masterdic_Index3003[0]), 0x3003},
};

const CONSTSTORE indextable * masterdic_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1016: i = 2;break;
		case 0x1017: i = 3;*callbacks = masterdic_Index1017_callbacks; break;
		case 0x1018: i = 4;break;
		case 0x1280: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1401: i = 7;break;
		case 0x1402: i = 8;break;
		case 0x1600: i = 9;break;
		case 0x1601: i = 10;break;
		case 0x1602: i = 11;break;
		case 0x1800: i = 12;*callbacks = masterdic_Index1800_callbacks; break;
		case 0x1801: i = 13;*callbacks = masterdic_Index1801_callbacks; break;
		case 0x1802: i = 14;*callbacks = masterdic_Index1802_callbacks; break;
		case 0x1A00: i = 15;break;
		case 0x1A01: i = 16;break;
		case 0x1A02: i = 17;break;
		case 0x1F20: i = 18;break;
		case 0x1F21: i = 19;break;
		case 0x1F22: i = 20;break;
		case 0x1F50: i = 21;break;
		case 0x1F51: i = 22;break;
		case 0x1F52: i = 23;break;
		case 0x1F53: i = 24;break;
		case 0x1F55: i = 25;break;
		case 0x2000: i = 26;*callbacks = position_1_callbacks; break;
		case 0x2001: i = 27;*callbacks = position_2_callbacks; break;
		case 0x2002: i = 28;*callbacks = position_3_callbacks; break;
		case 0x3000: i = 29;*callbacks = counter_1_callbacks; break;
		case 0x3001: i = 30;*callbacks = counter_2_callbacks; break;
		case 0x3003: i = 31;*callbacks = counter_3_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &masterdic_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status masterdic_PDO_status[3] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const CONSTSTORE quick_index masterdic_firstIndex = {
  0, /* SDO_SVR */
  5, /* SDO_CLT */
  6, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  12, /* PDO_TRS */
  15 /* PDO_TRS_MAP */
};

const CONSTSTORE quick_index masterdic_lastIndex = {
  0, /* SDO_SVR */
  5, /* SDO_CLT */
  8, /* PDO_RCV */
  11, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  17 /* PDO_TRS_MAP */
};

const CONSTSTORE UNS16 masterdic_ObjdictSize = sizeof(masterdic_objdict)/sizeof(masterdic_objdict[0]); 

CO_Data masterdic_Data = CANOPEN_NODE_DATA_INITIALIZER(masterdic);

