
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef __UPDATE_FIRMWARE_H__
#define __UPDATE_FIRMWARE_H__

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 update_firmware_valueRangeTest (UNS8 typeValue, void * value);
const indextable * update_firmware_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Slave node data struct, OD means Object Dictionary */
extern CO_Data update_firmware_ObjDictData;

#endif // __UPDATE_FIRMWARE_H__
