
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef __SLAVEDIC_H__
#define __SLAVEDIC_H__

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 slavedic_valueRangeTest (UNS8 typeValue, void * value);
const indextable * slavedic_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Slave node data struct, OD means Object Dictionary */
extern CO_Data slavedic_ObjDictData;
extern UNS32 counter0;    /* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER16 counter1;    /* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 counter2;    /* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 counter3;    /* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 counter4;    /* Mapped at index 0x2004, subindex 0x00*/
extern UNS32 position0;    /* Mapped at index 0x3000, subindex 0x00*/
extern UNS16 position1;    /* Mapped at index 0x3001, subindex 0x00*/
extern UNS8 position2;    /* Mapped at index 0x3002, subindex 0x00*/
extern UNS8 position3;    /* Mapped at index 0x3003, subindex 0x00*/
extern UNS16 position4;    /* Mapped at index 0x3004, subindex 0x00*/

#endif // __SLAVEDIC_H__
